### ISSUE TITLE
request.abort specific scripts

### ISSUE THREAD

**Issue by TrailError** [djkelleher/pyppeteer_spider#1]
In pyppeteer I usually abort external scripts for ads, google analytics and Facebook. I could not find any functionality for that in pyppeteer_spider. I do it like this in my scripts:

```python
abortList = ['facebook', 'google']

async def block_type(request):
    if request.resourceType in self.request_abort_types:
        await request.abort()
    elif any(item in request.url for item in self.abortList):
        await request.abort()
    else:
        await request.continue_()
```

I think it is an easy change to add that functionality, although I'm new to OOP and not sure how to implement it.

**Comment by djkelleher** [comment]
Cool idea. Currently in page.py request interception/abortion is implemented like:
```
          async def block_type(request):
                    if request.resourceType in self.request_abort_types:
                        await request.abort()
                    else:
                        await request.continue_()
```
so extensions like what you're suggesting can be easily implemented. I will look to update this in the coming week.

**Comment by djkelleher** [comment]
To get this functionality, you can pass your 'abortList' as argument 'blocked_urls' when constructing a Spider. This will internally use Network.setBlockedURLs (https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs) to block the URLs/URL patters.
